# ==============================================================================
# N o d e
# ==============================================================================
node:
  port: 8000

# ==============================================================================
# S U B G R A P H
# ==============================================================================
subgraph:
  authentication: http://localhost:3001/graphql
  event: http://localhost:3002/graphql
  invitation: http://localhost:3003/graphql
  ticket: http://localhost:3004/graphql
  notification: http://localhost:3005/graphql

# ==============================================================================
# K A F K A
# ==============================================================================
kafka:
  host: localhost
  groupId: omnixys-gateway-service
